name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: General SCM
      uses: actions/checkout@v1
    
    - name: generate and build
      run: |
        cmake . -B.build -Ax64
        cmake --build .build
      
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: SamByeol
        path: .build\app\Debug\app.exe

    - name: Upload to Discord
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        FILE_PATH: .build\app\Debug\app.exe
      run: |
        curl -H 'Content-Type: multipart/form-data' \
        -X POST \
        -F "file=@$FILE_PATH" $DISCORD_WEBHOOK
