name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: General SCM
      uses: actions/checkout@v1
    
    - name: Generate and Build
      run: |
        cmake . -B.build -Ax64
        cmake --build .build
      
    - name: Upload Artifact to Github
      uses: actions/upload-artifact@v1.0.0
      with:
        name: SamByeol_$GITHUB_SHA
        path: .build\app\Debug\app.exe
